name = "ReinforcedSnake"
uuid = "6e4a5d7c-cf5a-4fb7-bf17-26e7ab6a80e1"
authors = ["David Ma≈°ek"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.8"
